/** Fake products list */
export const fakeServices = [
  {
    id: 1,
    img: 'https://cdn.tgdd.vn/2021/03/CookProduct/2cachlammixaotrung-1200x676.jpg',
    name: 'Mì xào 2 gói',
    price: 10000,
    quantity: 10,
    catId: 1,
    unit: 'dĩa',
  },
  {
    id: 2,
    img: 'https://diadiemanuong.net.vn/www/uploads/images/properties/adminweb@gmail.com/08-2022/202283095742_khangdinh.jpg',
    name: 'Bánh mì',
    price: 5000,
    quantity: 7,
    catId: 1,
    unit: 'cái',
  },
  {
    id: 3,
    img: 'https://oola.vn/wp-content/uploads/2023/03/13.-Ca-phe-den.png',
    name: 'Cafe đen đá',
    price: 5000,
    quantity: 7,
    catId: 2,
    unit: 'ly',
  },
  {
    id: 4,
    img: 'https://nvcs.vn/upload/images/2019/10/20-1024x684.png',
    name: 'Thuốc lá',
    price: 5000,
    quantity: 11,
    catId: 3,
    unit: 'gói',
  },
  {
    id: 5,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 100k',
    price: 100000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 6,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 200k',
    price: 200000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 7,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 8,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 9,
    img: 'https://cdn.tgdd.vn/2021/03/CookProduct/2cachlammixaotrung-1200x676.jpg',
    name: 'Mì xào 2 gói',
    price: 10000,
    quantity: 10,
    catId: 1,
    unit: 'dĩa',
  },
  {
    id: 10,
    img: 'https://diadiemanuong.net.vn/www/uploads/images/properties/adminweb@gmail.com/08-2022/202283095742_khangdinh.jpg',
    name: 'Bánh mì',
    price: 5000,
    quantity: 7,
    catId: 1,
    unit: 'cái',
  },
  {
    id: 11,
    img: 'https://oola.vn/wp-content/uploads/2023/03/13.-Ca-phe-den.png',
    name: 'Cafe đen đá',
    price: 5000,
    quantity: 7,
    catId: 2,
    unit: 'ly',
  },
  {
    id: 12,
    img: 'https://nvcs.vn/upload/images/2019/10/20-1024x684.png',
    name: 'Thuốc lá',
    price: 5000,
    quantity: 11,
    catId: 3,
    unit: 'gói',
  },
  {
    id: 13,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 100k',
    price: 100000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 14,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 200k',
    price: 200000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 15,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 16,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 17,
    img: 'https://cdn.tgdd.vn/2021/03/CookProduct/2cachlammixaotrung-1200x676.jpg',
    name: 'Mì xào 2 gói',
    price: 10000,
    quantity: 10,
    catId: 1,
    unit: 'gói',
  },
  {
    id: 18,
    img: 'https://diadiemanuong.net.vn/www/uploads/images/properties/adminweb@gmail.com/08-2022/202283095742_khangdinh.jpg',
    name: 'Bánh mì',
    price: 5000,
    quantity: 7,
    catId: 1,
    unit: 'cái',
  },
  {
    id: 19,
    img: 'https://oola.vn/wp-content/uploads/2023/03/13.-Ca-phe-den.png',
    name: 'Cafe đen đá',
    price: 5000,
    quantity: 7,
    catId: 2,
    unit: 'ly',
  },
  {
    id: 20,
    img: 'https://nvcs.vn/upload/images/2019/10/20-1024x684.png',
    name: 'Thuốc lá',
    price: 5000,
    quantity: 11,
    catId: 3,
    unit: 'gói',
  },
  {
    id: 21,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 100k',
    price: 100000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 22,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 200k',
    price: 200000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 23,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 24,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 25,
    img: 'https://cdn.tgdd.vn/2021/03/CookProduct/2cachlammixaotrung-1200x676.jpg',
    name: 'Mì xào 2 gói',
    price: 10000,
    quantity: 10,
    catId: 1,
    unit: 'gói',
  },
  {
    id: 26,
    img: 'https://diadiemanuong.net.vn/www/uploads/images/properties/adminweb@gmail.com/08-2022/202283095742_khangdinh.jpg',
    name: 'Bánh mì',
    price: 5000,
    quantity: 7,
    catId: 1,
    unit: 'cái',
  },
  {
    id: 27,
    img: 'https://oola.vn/wp-content/uploads/2023/03/13.-Ca-phe-den.png',
    name: 'Cafe đen đá',
    price: 5000,
    quantity: 7,
    catId: 2,
    unit: 'ly',
  },
  {
    id: 28,
    img: 'https://nvcs.vn/upload/images/2019/10/20-1024x684.png',
    name: 'Thuốc lá',
    price: 5000,
    quantity: 11,
    catId: 3,
    unit: 'gói',
  },
  {
    id: 29,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 100k',
    price: 100000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 30,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 200k',
    price: 200000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 31,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 32,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 33,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 34,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'thẻ',
  },
  {
    id: 35,
    img: 'https://cdn.tgdd.vn/2021/03/CookProduct/2cachlammixaotrung-1200x676.jpg',
    name: 'Mì xào 2 gói',
    price: 10000,
    quantity: 10,
    catId: 1,
    unit: 'gói',
  },
  {
    id: 36,
    img: 'https://diadiemanuong.net.vn/www/uploads/images/properties/adminweb@gmail.com/08-2022/202283095742_khangdinh.jpg',
    name: 'Bánh mì',
    price: 5000,
    quantity: 7,
    catId: 1,
    unit: 'cái',
  },
  {
    id: 37,
    img: 'https://oola.vn/wp-content/uploads/2023/03/13.-Ca-phe-den.png',
    name: 'Cafe đen đá',
    price: 5000,
    quantity: 7,
    catId: 2,
    unit: 'ly',
  },
  {
    id: 38,
    img: 'https://nvcs.vn/upload/images/2019/10/20-1024x684.png',
    name: 'Thuốc lá',
    price: 5000,
    quantity: 11,
    catId: 3,
    unit: 'cái',
  },
  {
    id: 39,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 100k',
    price: 100000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 40,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 200k',
    price: 200000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 41,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 42,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 43,
    img: 'https://oola.vn/wp-content/uploads/2023/03/13.-Ca-phe-den.png',
    name: 'Cafe đen đá',
    price: 5000,
    quantity: 7,
    catId: 2,
    unit: 'cái',
  },
  {
    id: 44,
    img: 'https://nvcs.vn/upload/images/2019/10/20-1024x684.png',
    name: 'Thuốc lá',
    price: 5000,
    quantity: 11,
    catId: 3,
    unit: 'cái',
  },
  {
    id: 45,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 100k',
    price: 100000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 46,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 200k',
    price: 200000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 47,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 50k',
    price: 50000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
  {
    id: 48,
    img: 'https://timo.vn/wp-content/uploads/dai-ly-the-cao1.jpg',
    name: 'Thẻ game 500k',
    price: 500000,
    quantity: 3,
    catId: 4,
    unit: 'cái',
  },
];
